[package]
name = 'pallet-ibc'
version = "3.0.0-pre.0"
authors = ['Octopus Network <hi@oct.network>']
edition = '2021'
license = "Apache-2.0"
homepage = "https://oct.network"
repository 	= "https://github.com/octopus-network/substrate-ibc/"
description = "An IBC implementation on Substrate."
readme = "README.md"
build = 'build.rs'
# documentation = "https://docs.rs/pallet-ibc" // TODO

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[build-dependencies.substrate-wasm-builder]
branch = 'polkadot-v0.9.18'
git = 'https://github.com/paritytech/substrate.git'

[dependencies]
codec = { package = "parity-scale-codec", version = "3.0.0", default-features = false, features = ["derive"] }
scale-info = { version = "2.1.2", default-features = false, features = ["derive"] }
sp-runtime = { git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.18", default-features = false }
sp-std = { git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.18", default-features = false }
frame-benchmarking = { git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.18", default-features = false, optional = true }
frame-support = { git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.18", default-features = false }
frame-system = { git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.18", default-features = false }
sp-core = { git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.18", default-features = false }
sp-io = { git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.18", default-features = false }
sp-tracing = { git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.18", default-features = false }
log = { version = "0.4.0", default-features = false }
prost-types = { version = "0.9.0", default-features = false }
prost = { version = "0.9.0", default-features = false }
serde_json = { version = "1.0", default-features = false }
serde = { version = "1.0", default-features = false }
flex-error = { version = "0.4.4", default-features = false }
hex = {version = "0.4.0", default-features = false }

# ibc = { git = "https://github.com/octopus-network/ibc-rs.git", branch = "feature/ics20", default-features = false }
# ibc-proto = { git = "https://github.com/octopus-network/ibc-rs.git", branch = "feature/ics20", default-features = false }
ibc = { path = "../ibc-rs/modules", default-features = false }
ibc-proto = { path = "../ibc-rs/proto", default-features = false }
tendermint-proto = { version = "=0.23.6", default-features = false }
# beefy-light-client = { git = "https://github.com/octopus-network/beefy-light-client.git", branch="feature/v0.9.18", default-features = false }
beefy-light-client = { path = "../beefy-light-client", default-features = false }

[dev-dependencies]
hex = '0.4.0'
sha2 = '0.10.2'
serde = { version = "1.0" }
# ibc = { git = "https://github.com/octopus-network/ibc-rs.git", branch = "feature/ics20", features = ["mocks"]}
ibc = { path = "../ibc-rs/modules", features = ["mocks"]}
sp-io = { git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.18"}
sp-runtime = { git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.18" }
sp-std = { git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.18" }
sp-keyring = { git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.18" }
frame-support = { git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.18" }
chrono = "0.4.19"

[features]
default = ['std']
std = [
	'codec/std',
	'log/std',
	"scale-info/std",
	'frame-benchmarking/std',
	'frame-support/std',
	'frame-system/std',
	'sp-core/std',
	'sp-runtime/std',
	'sp-std/std',
	'sp-io/std',
	'sp-tracing/std',
	'prost-types/std',	
	'prost/std',
	'ibc/std',
	'ibc-proto/std',
	'beefy-light-client/std',
	'serde_json/std',
	'serde/std',	
	'flex-error/std',
	'hex/std',
]
runtime-benchmarks = ["frame-benchmarking"]
try-runtime = ["frame-support/try-runtime"]

[patch.crates-io]
