[package]
authors = ['Octopus Network <hi@oct.network>']
edition = '2018'
name = 'pallet-ibc'
version = "3.0.0-pre.0"
license = "Apache-2.0"
homepage = "https://oct.network"
repository = "https://github.com/octopus-network/substrate-ibc/"
description = "An IBC implementation on Substrate."
readme = "README.md"
documentation = "https://docs.rs/pallet-ibc"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
codec = { package = "parity-scale-codec", version = "2.0.0", default-features = false, features = ["derive"] }
frame-support = { default-features = false, version = "3.0.0" }
frame-system = { default-features = false,  version = "3.0.0" }
frame-benchmarking = { default-features = false,  version = "3.1.0", optional = true }

serde = { version = "1.0.101", optional = true }
log = { version = "0.4.0", default-features = false }
sp-core = { default-features = false, version = "3.0.0" }
sp-runtime = { default-features = false, version = "3.0.0" }
sp-std = { default-features = false, version = "3.0.0" }

ibc = { git = "https://github.com/octopus-network/ibc-rs.git", branch = "dv-grandpa-client-dev" }

prost = "0.7"
prost-types = "0.7"
tendermint-proto = "=0.21.0"

[dev-dependencies]
hex = '0.4.0'
sha2 = '0.9.3'

[features]
default = ['std']
std = [
	'codec/std',
	'frame-support/std',
	'frame-system/std',
	'frame-benchmarking/std',
	'serde',
	'sp-core/std',
	'sp-runtime/std',
	'sp-std/std',
	'log/std',
]

runtime-benchmarks = ["frame-benchmarking"]
try-runtime = ["frame-support/try-runtime"]
