[package]
authors = ['Cdot Network <https://cdot.network>']
description = 'An IBC implementation on Substrate.'
edition = '2018'
homepage = 'https://cdot.network'
license = 'Apache-2.0'
name = 'pallet-ibc'
repository = 'https://github.com/cdot-network/substrate-ibc/'
version = '2.0.0-rc6'

[package.metadata.docs.rs]
targets = ['x86_64-unknown-linux-gnu']

[dependencies.codec]
default-features = false
features = ['derive']
package = 'parity-scale-codec'
version = '1.3.4'

[dependencies.finality-grandpa]
default-features = false
features = ['derive-codec']
version = '0.12.3'

[dependencies.frame-support]
default-features = false
git = 'https://github.com/paritytech/substrate.git'
tag = 'v2.0.0-rc6'
version = '2.0.0-rc6'

[dependencies.frame-system]
default-features = false
git = 'https://github.com/paritytech/substrate.git'
tag = 'v2.0.0-rc6'
version = '2.0.0-rc6'

[dependencies.hash-db]
default-features = false
version = '0.15.2'

[dependencies.serde]
default-features = false
optional = true
version = '1.0.102'

[dependencies.sp-core]
default-features = false
git = 'https://github.com/paritytech/substrate.git'
tag = 'v2.0.0-rc6'
version = '2.0.0-rc6'

[dependencies.sp-finality-grandpa]
default-features = false
git = 'https://github.com/paritytech/substrate.git'
tag = 'v2.0.0-rc6'
version = '2.0.0-rc6'

[dev-dependencies.sp-io]
default-features = false
git = 'https://github.com/paritytech/substrate.git'
tag = 'v2.0.0-rc6'
version = '2.0.0-rc6'

[dependencies.sp-runtime]
default-features = false
git = 'https://github.com/paritytech/substrate.git'
tag = 'v2.0.0-rc6'
version = '2.0.0-rc6'

[dependencies.sp-std]
default-features = false
git = 'https://github.com/paritytech/substrate.git'
tag = 'v2.0.0-rc6'
version = '2.0.0-rc6'

[dependencies.sp-trie]
default-features = false
git = 'https://github.com/paritytech/substrate.git'
tag = 'v2.0.0-rc6'
version = '2.0.0-rc6'

[features]
default = ['std']
std = [
    'codec/std',
    'finality-grandpa/std',
    'frame-support/std',
    'frame-system/std',
    'hash-db/std',
    'serde',
    'sp-core/std',
    'sp-finality-grandpa/std',
    'sp-runtime/std',
    'sp-std/std',
    'sp-trie/std',
]
