[package]
authors = ['Octopus Network <hi@oct.network>']
edition = '2021'
name = 'pallet-ibc'
version = "3.0.0-pre.0"
license = "Apache-2.0"
homepage = "https://oct.network"
repository = "https://github.com/octopus-network/substrate-ibc/"
description = "An IBC implementation on Substrate."
readme = "README.md"
build       = 'build.rs'
documentation = "https://docs.rs/pallet-ibc"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[build-dependencies.substrate-wasm-builder]
branch = 'polkadot-v0.9.12'
git    = 'https://github.com/paritytech/substrate.git'

[dependencies]
codec 					= { package = "parity-scale-codec", version = "2.0.0", default-features = false, features = ["derive"] }
log 					= { version = "0.4.0", default-features = false }
scale-info 				= { version = "1.0", default-features = false, features = ["derive"] }

frame-benchmarking 		= { git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.12", default-features = false, optional = true }
frame-support 			= { git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.12", default-features = false }
frame-system 			= { git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.12", default-features = false }
sp-core 				= { git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.12", default-features = false }
sp-runtime 				= { git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.12", default-features = false }
sp-std 					= { git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.12", default-features = false }
sp-io 					= { git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.12", default-features = false }

ibc 					= { git = "https://github.com/octopus-network/ibc-rs.git", branch = "dv-update-subxt", default-features = false }
#ibc = { path = "../ibc-rs/modules", default-features = false }

prost-types 			= { package = "informalsystems-prost-types", version = "0.8.1", default-features = false }
tendermint-proto 		= { version = "0.22.0", default-features = false }

[dev-dependencies]
hex = '0.4.0'
sha2 = '0.9.3'
serde = { version = "1.0" }
sp-io = { git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.12"}
sp-runtime = { git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.12" }
sp-std = { git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.12" }

[features]
default = ['std']
std = [
	'codec/std',
	'log/std',
	"scale-info/std",
	'frame-benchmarking/std',
	'frame-support/std',
	'frame-system/std',
	'sp-core/std',
	'sp-runtime/std',
	'sp-core/std',
	'sp-std/std',
	'ibc/std',
	'prost-types/std',
	'tendermint-proto/std',
]

runtime-benchmarks = ["frame-benchmarking"]
try-runtime = ["frame-support/try-runtime"]

[patch.crates-io]

# for tendermint
tendermint              = { git = "https://github.com/informalsystems/tendermint-rs", rev = "4f6ef3d6" }
tendermint-rpc          = { git = "https://github.com/informalsystems/tendermint-rs", rev = "4f6ef3d6" }
tendermint-proto        = { git = "https://github.com/informalsystems/tendermint-rs", rev = "4f6ef3d6" }
tendermint-light-client = { git = "https://github.com/informalsystems/tendermint-rs", rev = "4f6ef3d6" }
tendermint-testgen      = { git = "https://github.com/informalsystems/tendermint-rs", rev = "4f6ef3d6" }
ics23                   = { git = "https://github.com/informalsystems/ics23.git", rev = "4461b673" }
safe-regex          = { git = "https://github.com/informalsystems/safe-regex.git", rev = "842d31f5" }
safe-regex-macro    = { git = "https://github.com/informalsystems/safe-regex.git", rev = "842d31f5" }
safe-regex-compiler = { git = "https://github.com/informalsystems/safe-regex.git", rev = "842d31f5" }
safe-quote          = { git = "https://github.com/informalsystems/safe-regex.git", rev = "842d31f5" }
safe-proc-macro2    = { git = "https://github.com/informalsystems/safe-regex.git", rev = "842d31f5" }
tonic = { package = "informalsystems-tonic", git = "https://github.com/informalsystems/tonic.git", rev = "99edfe23" }
