[package]
name = "pallet-ics20-transfer"
version = "0.1.0"
description = "FRAME pallet ibc protocol ics20 token transfer"
authors = ["Octopus Network <hi@oct.network>"]
homepage = "https://github.com/octopus-network"
edition = "2021"
license = "Unlicense"
publish = false
repository = "https://github.com/octopus-network/substrate-ibc"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
# local libraries
ibc-support = { version = "0.1.0", default-features = false, path = "../../ibc-support" }
# third-party crates
hex = {version = "0.4.0", default-features = false }
# substrate crates
codec = { package = "parity-scale-codec", version = "3.0.0", default-features = false, features = [
	"derive",
] }
scale-info = { version = "2.1.1", default-features = false, features = ["derive"] }
log = { version = "0.4", default-features = false }
frame-benchmarking = { version = "4.0.0-dev", default-features = false, optional = true, git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.28" }
frame-support = { version = "4.0.0-dev", default-features = false, git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.28" }
frame-system = { version = "4.0.0-dev", default-features = false,git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.28" }
sp-runtime = { version = "6.0.0", default-features = false, git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.28" }
sp-io = { version = "6.0.0", default-features = false, git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.28" }
## for ibc protocl
ibc = { version = "0.19.0", default-features = false, branch = "main", git = "https://github.com/cosmos/ibc-rs.git" }
ibc-proto = { version = "0.20.1", default-features = false }
tendermint-proto = { version = "=0.25.0", default-features = false }

[dev-dependencies]
sp-core = { version = "6.0.0", default-features = false, git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.28" }
sp-io = { version = "6.0.0", default-features = false, git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.28" }
sp-runtime = { version = "6.0.0", default-features = false, git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.28" }

[features]
default = ["std"]
std = [
	"hex/std",
	"codec/std",
	"log/std",
	"frame-benchmarking/std",
	"frame-support/std",
	"frame-system/std",
	"scale-info/std",
	"ibc/std",
	"ibc-proto/std",
	"ibc-support/std",
	"sp-runtime/std",
	"sp-io/std",
]
runtime-benchmarks = ["frame-benchmarking/runtime-benchmarks"]
try-runtime = ["frame-support/try-runtime"]
